- README.md
- bin/setup
- docs/00_setup_guide.md
- docs/01_getting_started.md
- docs/02_ce-registry_walkthrough.md
- docs/05_backup_and_restore.md
Fix minor issues which came up while going through the Documentation
> Getting started

- README.md
The URLs/badges were all pointing to learningtapestry/learningregistry
> Update badges URLs

- bin/send_resource_envelope
- bin/update_json_schemas
Add two helper scripts
1. updating the CE/R json schemas
2. publishing a resource envelope
> Helper scripts

- bin/send_resource_envelope
Fixing https://github.com/CredentialEngine/CredentialRegistry/pull/46#issuecomment-290372847
> Move envelopes url into a const

- docs/08_schemas.md
- docs/99_developer_notes.md
> Documentation

- .cloud66/install_swagger.sh
Forgot to update the swagger-ui installation script for cloud66 in #63
> Update swagger UI on cloud66

- bin/update_json_schemas
- fixtures/schemas/ce_registry/assessment_profile.json
- fixtures/schemas/ce_registry/credential.json
- fixtures/schemas/ce_registry/learning_opportunity_profile.json
- fixtures/schemas/ce_registry/organization.json
- spec/support/fixtures/json/ce_registry/organization/1_valid.json
Updated JSON Schemas for `ce_registry`
> Update json schemas

- fixtures/schemas/ce_registry/credential.json
- fixtures/schemas/ce_registry/organization.json
> Update the JSON Schemas for ce_registry

- fixtures/configs/ce_registry.json
> Update full text search fields

- fixtures/configs/ce_registry.json
> Add missing schema configuration

- bin/update_json_schemas
- Use OptionParser
- Add directory name parameter
- Specify default schema directory name
> (#131, #153) Improve update_json_schemas script

- graphql-examples.md
- graphql-spec.md
Includes a specification document, plus examples, for the design and features of the new graph-based search and GraphQL endpoint.
> GraphQL Spec + Examples

- app/services/query_gremlin.rb
Resolves learningtapestry/CredentialRegistry#8
> Log Gremlin queries

- .gitignore
- config/application.rb
- lib/tasks/db.rake
with objective of making extensions restorable
> Switch from custom to plain PG dumps

- app/services/query_gremlin.rb
Ref. CredentialEngine/CredentialRegistry#245
> Return correct HTTP status when Gremlin query times out

- lib/tasks/envelopes.rake
…use single DELETE statement per each involved model
Ref. CredentialEngine/CredentialRegistry#233
> Improve envelopes:clear_all task

- app/api/v1/schemas.rb
Ref. CredentialEngine/CredentialRegistry#243
> Fix name validation in PUT /schemas/:schema_name

- app/api/entities/envelope.rb
- lib/swagger_docs.rb
- spec/api/v1/envelopes_spec.rb
- spec/api/v1/publish_spec.rb
- spec/spec_helper.rb
Ref. CredentialEngine/CredentialRegistry#231
> Add `changed` flag to publishing endpoints' responses

- db/migrate/20181107021512_add_unique_ctid_to_envelopes.rb
- db/migrate/20190919121231_change_scope_of_ctid_index_in_envelopes.rb
- db/structure.sql
- lib/migration_helpers.rb
- spec/models/envelope_spec.rb
Ref. CredentialEngine/CredentialRegistry#259
> Make CTIDs unique across envelope communities

- Gemfile
- Gemfile.lock
- app/api/helpers/shared_helpers.rb
- app/api/v1/envelopes.rb
- app/api/v1/graph.rb
- app/api/v1/resources.rb
- app/api/v1/search.rb
- app/services/validate_api_key.rb
- config/application.rb
- db/migrate/20191024081858_add_secured_to_envelope_communities.rb
- db/structure.sql
- spec/api/v1/envelopes_spec.rb
- spec/api/v1/graph_spec.rb
- spec/api/v1/resources_spec.rb
- spec/api/v1/search_spec.rb
- spec/services/validate_api_key_spec.rb
Ref. CredentialEngine/CredentialRegistry#270
> Secured communities

- .cloud66/deploy_hooks.yml
- .cloud66/manifest.yml
Resolves CredentialEngine/CredentialRegistry#286
> Fix deploy configuration

- .cloud66/deploy_hooks.yml
- .cloud66/install_new_relic_agent.sh
- .env
- Gemfile
- Gemfile.lock
- config/skylight.yml
This PR configures agents for [New Relic Infrastructure](https://newrelic.com/products/infrastructure) and [Skylight](skylight.io).
> Monitoring tools

- Gemfile
- Gemfile.lock
- Rakefile
- app/api/v1/publish.rb
- app/services/envelope_builder.rb
- app/services/publish_interactor.rb
- app/validators/original_user_validator.rb
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- spec/api/v1/publish_spec.rb
- spec/factories/envelopes.rb
- spec/factories/resources.rb
- spec/spec_helper.rb
Implements CredentialEngine/CredentialRegistry#283
> Add ability to transfer ownership of document

- app/api/v1/publish.rb
- app/models/envelope.rb
- app/services/purge_envelopes.rb
- app/services/rdf_indexer.rb
- app/services/tokenize_rdf_data.rb
- db/migrate/20200601094240_add_purged_at_to_envelopes.rb
- db/structure.sql
- lib/tasks/envelopes.rake
- spec/api/v1/publish_spec.rb
- spec/services/purge_envelopes_spec.rb
…to ensure data is removed from Gremlin and Neptune
Fixes CredentialEngine/CredentialRegistry#328
> Delaye envelope purge

- spec/models/searchable_spec.rb
Ref. CredentialEngine/CredentialRegistry#332
> Fix searchable specs for Cost Manifest and Learning Opportunity

- app/api/entities/description_set.rb
- app/api/v1/base.rb
- app/api/v1/description_sets.rb
- app/models/description_set.rb
- app/services/convert_bnode_to_uri.rb
- app/services/precalculate_description_sets.rb
- app/services/rdf_indexer.rb
- db/migrate/20200727085544_create_description_sets.rb
- db/structure.sql
- fixtures/description_set_item_maps.yml
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- spec/api/v1/description_sets_spec.rb
- spec/factories/description_sets.rb
Ref. CredentialEngine/CredentialRegistry#342
> Description sets

- app/api/v1/resources.rb
- lib/swagger_docs.rb
- spec/api/v1/resources_spec.rb
Ref. CredentialEngine/CredentialRegistry#352
> Enable getting bnodes in bulk

- app/services/precalculate_description_sets.rb
- fixtures/description_set_item_maps.yml
Ref. CredentialEngine/CredentialRegistry#357
Fix CredentialEngine/CredentialRegistry#358
> Description set updates

- app/services/tokenize_rdf_data.rb
Ref. CredentialEngine/CredentialRegistry#365
> Fix plain string tokenization

- app/services/precalculate_description_sets.rb
Ref. CredentialEngine/CredentialRegistry#357
> Add ASN prefix to description set SPARQL queries

- app/api/v1/defaults.rb
- app/api/v1/publish.rb
- config/airbrake.rb
- spec/api/v1/publish_spec.rb
> Fix authentication in documents API

- app/api/v1/envelopes.rb
- app/api/v1/publish.rb
- app/models/envelope.rb
- app/services/publish_interactor.rb
- app/services/rdf_indexer.rb
- db/migrate/20201012074942_add_publishing_organization_to_envelopes.rb
- db/structure.sql
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- spec/api/v1/envelopes_spec.rb
- spec/api/v1/publish_spec.rb
- spec/schemas/ce_registry_assessment_profile_spec.rb
Ref. CredentialEngine/CredentialRegistry#364
> Publishing metadata

- lib/tasks/dumps.rake
Ref. CredentialEngine/CredentialRegistry#323
> Allow exempting communities from backing up

- app/api/v1/organizations.rb
- app/models/organization.rb
- lib/swagger_docs.rb
- spec/api/v1/organizations_spec.rb
Ref. CredentialEngine/CredentialRegistry#384
> Add endpoint for listing envelopes owned by organization

- app/api/entities/envelope_resource.rb
- app/services/search.rb
Ref. CredentialEngine/CredentialRegistry#364
> Expose publishing metadata in search API

- app/services/search.rb
- lib/swagger_helpers.rb
- spec/api/v1/search_spec.rb
Ref. CredentialEngine/CredentialRegistry#392
> Implement faceted search

- app/api/helpers/shared_helpers.rb
- app/api/v1/search.rb
- db/migrate/20200813121714_add_secured_search_to_envelope_communities.rb
- db/structure.sql
- spec/api/v1/search_spec.rb
Ref. CredentialEngine/CredentialRegistry#341
> Ability to restrict FTS on community basis

- app/services/precalculate_description_sets.rb
Ref. CredentialEngine/CredentialRegistry#400
> Include reverse mappings when pre-calculating description sets

- app/api/entities/description_set_data.rb
- app/api/entities/description_set_group.rb
- app/services/fetch_description_set_data.rb
- spec/api/v1/description_sets_spec.rb
Ref. CredentialEngine/CredentialRegistry#399
> Group description sets by CTID

- app/api/entities/envelope_community_config.rb
- app/api/entities/envelope_community_config_version.rb
- app/api/v1/base.rb
- app/api/v1/config.rb
- app/api/v1/schemas.rb
- app/models/envelope_community.rb
- app/models/envelope_community_config.rb
- db/migrate/20210121082610_create_envelope_community_configs.rb
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- spec/api/v1/config_spec.rb
- spec/api/v1/schemas_spec.rb
- spec/factories/envelope_community_configs.rb
- spec/factories/json_schemas.rb
Ref. CredentialEngine/CredentialRegistry#289, CredentialEngine/CredentialRegistry#380
> Config and schema APIs

- app/api/v1/base.rb
- app/api/v1/bulk_purge.rb
- app/models/organization.rb
- db/migrate/20210311135955_change_envelope_foreign_keys_on_delete.rb
- db/structure.sql
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- spec/api/v1/bulk_purge_spec.rb
Ref. CredentialEngine/CredentialRegistry#412
> Bulk purge API

- app/services/search.rb
Ref. CredentialEngine/CredentialRegistry#429
> Match envelope's value when applying resource type filter in FTS

- app/services/precalculate_description_sets.rb
Ref. CredentialEngine/CredentialRegistry#445
> Specify subject's type when processing reverse description set mappings

- app/services/search.rb
Ref. CredentialEngine/CredentialRegistry#453
> Revert top-level resource type constraint in FTS

- app/services/search.rb
- lib/swagger_docs.rb
- lib/swagger_helpers.rb
- Default to false
- Add `only` option
- Update Swagger docs
> Improve bnode filter in search API

- app/api/entities/envelope.rb
- lib/swagger_docs.rb
- spec/api/v1/envelopes_spec.rb
- spec/api/v1/publish_spec.rb
This reverts commit 6cee7625c1047dc50ba49510d5fe4a27759d147f.
> Revert "Remove changed flag from Envelope entity"

- app/services/ctdl_query.rb
Ref CredentialEngine/CredentialRegistry#539
> Enable 'no value' conditions in CTDL queries

- app/services/ctdl_query.rb
- app/services/ctdl_subclasses_resolver.rb
- bin/update_ctdl_subclasses_map
- fixtures/subclasses_map.json
{
"@type": {
"search:value": "ceterms:Credential",
"search:matchType": "search:subClassOf"
}
}
> Allow to expand subclasses in CTDL queries.

- app/api/entities/envelope.rb
- app/api/entities/envelope_resource.rb
- app/api/v1/publish.rb
- app/api/v2/publish.rb
- app/jobs/publish_envelope_job.rb
- app/models/envelope.rb
- app/models/indexed_envelope_resource.rb
- app/models/publish_request.rb
- app/services/ctdl_query.rb
- app/services/publish_interactor.rb
- app/services/run_ctdl_query.rb
- app/services/search.rb
- db/migrate/20220315122626_add_resource_publish_type_to_envelopes.rb
- db/migrate/20220315190000_add_search_record_publish_type_to_indexed_envelope_resources.rb
- db/structure.sql
- spec/factories/envelopes.rb
- spec/services/index_envelope_resource_spec.rb
https://github.com/CredentialEngine/CredentialRegistry/issues/502
> Allow to specify and filter by resource publish type (primary|secondary)

- app/services/index_envelope_resource.rb
- spec/services/index_envelope_resource_spec.rb
Ref. CredentialEngine/CredentialRegistry#570
> Fix indexing of single object subresources

- app/services/ctdl_query.rb
Ref. CredentialEngine/CredentialRegistry#572
> Make `search:exactMatch` conditions strict

- app/services/ctdl_query.rb
Ref. CredentialEngine/CredentialRegistry#572
> Add `search:contains` match type to CTDL engine

- app/services/ctdl_query.rb
Ref. CredentialEngine/CredentialRegistry#579
> Exclude partial resources from CTDL search results

- app/services/ctdl_query.rb
Ref. CredentialEngine/CredentialRegistry#581
> Enable search:anyValue and search:noValue conditions for ID properties

- app/api/v1/resources.rb
- app/models/envelope_community.rb
- lib/swagger_docs.rb
- spec/api/v1/resources_spec.rb
Ref. CredentialEngine/CredentialRegistry#586
> Add API for checking existence of resources

- app/models/organization.rb
- lib/swagger_helpers.rb
- spec/api/v1/organizations_spec.rb
Ref. CredentialEngine/CredentialRegistry#587
> Allow deleting organizations having only deleted envelopes

- app/services/ctdl_query.rb
Ref. CredentialEngine/CredentialRegistry#597
> Remove trailing slash from URI conditions

- app/api/entities/description_set_data.rb
- app/services/fetch_description_set_data.rb
- app/services/precalculate_description_sets.rb
- spec/api/v1/description_sets_spec.rb
…even when it's empty if subresources are requested
> Expose description_set_resources property

- app/api/entities/envelope.rb
- app/api/v1/single_envelope.rb
- app/models/envelope.rb
- db/migrate/20230515091128_add_last_verified_on_to_envelopes.rb
- db/structure.sql
- lib/swagger_docs.rb
- spec/api/v1/envelopes_spec.rb
- spec/api/v1/publish_spec.rb
- spec/api/v1/single_envelope_spec.rb
- spec/models/envelope_spec.rb
Ref. CredentialEngine/CredentialRegistry#503
> Last verification date to envelopes

- fixtures/subclasses_map.json
Ref. CredentialEngine/CredentialRegistry#644
> Update subclass mapping

- app/services/ctdl_query.rb
- app/services/ctdl_subclasses_resolver.rb
Ref. CredentialEngine/CredentialRegistry#644
> Include subclasses mapping into envelope community config

- app/services/ctdl_query.rb
> Replace CTE with subqueries

- app/services/ctdl_query.rb
- config/application.rb
- config/arel_nodes_cte.rb
> Combine materialized CTEs with JOINs for reference conditions

- app/services/find_uri_aliases.rb
> Return original value as is when URI resolver fails to find aliases

- app/api/v1/resources.rb
- app/services/fetch_envelope_resource.rb
> Inject graph bnodes into resource documents

- app/services/ctdl_query.rb
> Support negative conditions in CTDL queries

- app/services/ctdl_query.rb
> Implement search:noValue for reference conditions

- fixtures/description_set_item_maps.yml
> Add *Embodied paths to description set mapping config

- app/services/ctdl_query.rb
- app/services/run_ctdl_query.rb
> Replace OR with UNION in term group conditions

- app/services/ctdl_query.rb
> Fix resolution of multiple subclassOf conditions

- .github/workflows/sonarqube.yaml
- app/api/v1/ctdl.rb
- app/services/ctdl_query.rb
- app/services/run_ctdl_query.rb
- db/migrate/20240916114729_create_ctdl_ts_rank_function.rb
- db/structure.sql
- sonar-project.properties
> Improve sorting by relevance in CTDL engine

- app/services/ctdl_query.rb
- app/services/run_ctdl_query.rb
> Fix total count in CTDL queries with zero results taken

- app/api/v1/envelopes.rb
- spec/api/v1/single_envelope_spec.rb
> Allow to fetch envelopes by their resources' IDs

- app/api/v1/resources.rb
- app/services/fetch_envelope_resource.rb
- spec/api/v1/resources_spec.rb
> (#713) Improve fetching envelope resources

- app/api/entities/node_headers.rb
- app/api/entities/version.rb
- config/application.rb
- spec/api/v1/envelopes_spec.rb
> (#729) Serialize timestamps in node headers using ISO 8601

- fixtures/description_set_item_maps.yml
> (#728) Fix progression level and model paths for competencies and their frameworks

- app/models/json_context.rb
- app/services/index_envelope_resource.rb
- lib/tasks/json_contexts.rake
- spec/services/index_envelope_resource_spec.rb
- Take resource context into account
> Sync context before indexing

- app/services/ctdl_query.rb
CredentialEngine/CLLC-Registry#3
> Deduplicate results of CTDL queries with OR conditions

- app/api/v1/base.rb
- app/api/v1/indexed_resources.rb
- app/models/envelope_community.rb
- lib/swagger_docs.rb
- lib/swagger_docs/models.rb
- lib/swagger_docs/sections/indexed_resources.rb
> Indexed resources API

- app/models/organization.rb
- spec/api/v1/organizations_spec.rb
- spec/factories/organizations.rb
> (#795) Validate organization CTID

- app/services/ctdl_subclasses_resolver.rb
- fixtures/configs/ce_registry.json
> (#829) Add default subclass mapping into default CER config

- app/services/index_envelope_resource.rb
> (#830) Ignore unreachable context URLs when indexing

- lib/swagger_docs.rb
- lib/swagger_docs/sections/description_sets.rb
- lib/swagger_docs/sections/envelopes.rb
- lib/swagger_docs/sections/graphs.rb
- lib/swagger_docs/sections/indexer.rb
- lib/swagger_docs/sections/resources.rb
- lib/swagger_docs/sections/search.rb
> (#820) Deduplicate Swagger defs and add missing ones

- docs/10_community-config.md
- docs/97_create_registry_containers.md
> (#841) Document community config

- lib/swagger_docs.rb
- lib/swagger_docs/sections/envelopes.rb
- lib/swagger_docs/sections/general.rb
- lib/swagger_docs/sections/graphs.rb
- lib/swagger_docs/sections/resources.rb
- lib/swagger_docs/sections/schemas.rb
- lib/swagger_docs/sections/search.rb
> (#851) Define security requirements in Swagger

- .github/workflows/test.yaml
This fix will correct the SQ scan and upload report.
> fix SQ scan/report upload

- .github/workflows/test.yaml
- Dockerfile
- docker-compose.yml
- docs/97_create_registry_containers.md
- docs/local_testing.md
We're adding further improvements to the Dockerfile security posture.
> Hardening dockerfile ENV & ARG

- app/services/ctdl_query.rb
> (#892) Fix ordering by resource properties in CTDL search

- app/api/v1/resources.rb
- spec/factories/envelope_resources.rb
- spec/services/extract_envelope_resources_spec.rb
> (#894) Optimize CTID lookup
