app/api/v1/envelope_helpers.rb
app/api/v1/resources_api.rb
spec/api/v1/resources_spec.rb

The retrieval of a resource with a full URL as the ID was broken, as grape interpreted a dot (`.`) in the URL as a format (such as `.html`).
The fix is not exactly pretty but the whole area is subject to change with the default community (#36) and `@id` prefix (#42) still unresolved.

Fix resources retrieval with a full URL as ID

---

app/api/helpers/shared_helpers.rb
app/api/v1/base.rb
app/api/v1/community_helpers.rb
app/api/v1/community_resources.rb
app/api/v1/envelope_helpers.rb
app/api/v1/resources_api.rb
app/models/envelope.rb
app/models/envelope_community.rb
config/application.rb
config/envelope_communities.json
db/seeds.rb
docs/01_getting_started.md
docs/02_ce-registry_walkthrough.md
spec/api/v1/community_resources_spec.rb
spec/models/envelope_community_spec.rb
spec/models/envelope_spec.rb

* The overall default community is (currently) set in the database (see example in [seeds.rb](../blob/ff498c3d0ffb64d633b0bc22e5166c893fa17234/db/seeds.rb#L3)).
* Host specific default communities can be configured in [`config/envelope_communities.json`](../blob/a7e26d4542e0861e1b62fcdcd510819be510e378/config/envelope_communities.json)
Implements #36

Default community

---

docs/02_ce-registry_walkthrough.md

Update the documentation (walkthrough) to favor the new `/resources` API endpoint over the old `/envelopes`.
Fixes #60

Resources docs

---

.cloud66/deploy_hooks.yml
.cloud66/log_files.yml.erb
.gitignore

`remote_syslog2` doesn't do any erb style interpolation like the
documentation led me to believe.

Fix papertrail logging setup

---

.cloud66/deploy_hooks.yml

The previous deploy_hook for Cloud66 didn't work

Fix Cloud66 deploy_hook

---

app/models/envelope.rb
spec/models/envelope_spec.rb

Make retrieval of resources by ID case-insensitive.
While UUIDs should be in lower case in general, a human might try to retrieve a resource with upper case IDs.
Related to #118

Retrieve resources with case-insensitive ID

---

app/models/envelope.rb
spec/models/envelope_spec.rb

Reverts CredentialEngine/CredentialRegistry#119
The introduced changes appear to create a lot of load in postgres which are slowing down the API.
Related to #123

Revert "Retrieve resources with case-insensitive ID"

---

app/api/v1/resources_api.rb
app/models/envelope.rb
app/services/envelope_builder.rb
spec/api/v1/resources_spec.rb

Allow users to update an existing resource without knowledge of it's `envelope_id` using a `POST` request.
Fixes #99

Update existing resource without envelope id

---

fixtures/configs/ce_registry.json
spec/api/v1/resources_spec.rb
spec/factories/resources.rb
spec/models/envelope_community_spec.rb
spec/support/fixtures/json/ce_registry/credential/1_valid.json

Related to #118 change `@id` prefix from `credentialengine.org` to `credentialengineregistry.org`.

Change CR prefix

---

Gemfile
Gemfile.lock
app/services/search.rb
lib/swagger_helpers.rb
spec/services/search_spec.rb
spec/support/shared_contexts/envelopes_for_search.rb

- Allows to sort search results by the `created_at` or `updated_at` timestamps.
- Sets the default sort order to `updated_at DESC`.

(#138) Allow to sort search results by timestamps

---

.gitignore
config/application.rb
lib/tasks/db.rake

Flow for backup/restore similar to UB
run once on the server: `psql -d template1 -c 'create extension pg_trgm;'`
- to backup:
`bin/rake db:backup`
- to restores:
place the dump on `db/content/content.dump`
then `bin/rake db:restore`

Tasks for db backup/restore flow

---

app/models/key_pair.rb
app/models/organization.rb
app/models/organization_publisher.rb
app/services/publish_interactor.rb
db/migrate/20171121222132_move_key_pairs.rb
db/structure.sql

KeyPairs are no longer linked to the OrganizationPublisher join model,
they belong to the Organization model now, so multiple publishers
publishing on behalf of the same Organization will now use the same key.

Link KeyPair to Organization model

---

.rubocop.yml
app/models/key_pair.rb
app/services/publish_interactor.rb
lib/exceptions.rb

The PublishInteractor needed a bit of refactoring to get its methods
under this limit.

Lower rubocop's method length limit

---

app/api/entities/envelope.rb
app/api/v1/publish.rb
app/models/publisher.rb
app/services/publish_interactor.rb
db/migrate/20171215172051_add_secondary_publisher.rb
db/structure.sql
spec/api/v1/resources_spec.rb

We now store a secondary publisher in envelopes, if it was provided with the request.

Secondary publishers

---

Gemfile
Gemfile.lock
app/services/internet_archive.rb
lib/tasks/dumps.rake

- Add missing dependency to Gemfile
Archive.org tasks depend on `rest-client`. That dependency was available in development by coincidence (Airbone depends on it), but not in actual deployments.
- Add header for auto-creating buckets
S3 PUTs would fail if the bucket were not created beforehand. Ref. https://archive.org/help/abouts3.txt
- Add task for backing up historical data
`backup_all` will loop through all the dates that have envelopes and call the backup task for them.

Fix backups task

---

config/application.rb

I often need to start Neo4J for doing things completely unrelated to the GraphQL search features (for example, running rake tasks).
Proposal: try to create the Neo4J session when booting up, but back down from it if we can't connect.

Don't depend on Neo4J for starting the application

---

app/models/extensions/gremlin_indexable.rb

Ref CredentialEngine/CredentialRegistry#229
There is a race condition when persisting resources, leading to the indexer being notified before the transaction is committed. That prevents the changes from appearing in the index in a timely manner.

Notify Gremlin indexer after transaction is actually committed

---

.rubocop.yml
Gemfile
Gemfile.lock
app/models/key_pair.rb

This avoids errors when path has spaces or other type of character that
needs escaping.

Escape SSH key paths when calling 'ssh-keygen'

---

app/api/v1/base.rb

This fixes 'Incomplete response' errors when hitting certain nonexistent routes

Remove 'plain' mounts of reusable APIs

---

sonar-project.properties

This PR makes the following changes:
- Adds a `sonar-project.properties` file that instructs the SonarQube scanner how to perform its analysis.
- Configures test coverage using the `simplecov` gem. Results are then uploaded to SonarQube as well.
Once you're ready to merge this PR, you can enable the code analysis through CodeShip. This is basically a two-step process:
1. Call the `scanner-ruby.sh` script from our [GitHub repository](https://github.com/learningtapestry/sonarqube-integrations). You can use `curl` or `wget` as suggested, or invoke it however you'd like. It's probably also generic enough to adapt to any typical ruby/rails project, at least for now.
2. Create an environment variable in CodeShip called `SONAR_TOKEN` that contains the token used to authenticate to the server. …

Sonarqube integration

---

app/api/v1/sparql.rb
app/services/query_sparql.rb
db/migrate/20210601020245_create_query_logs.rb
db/structure.sql
spec/api/v1/sparql_spec.rb

We ping the `/sparql` endpoint with a simple query every minute in order to monitor Neptune's availability. It would be nice not to pollute the query log with those queries. I can imagine other situations when we don't want to log query requests. So let's make logging optional (enabled by default, of course).

Make query logging optional

---

app/models/query_log.rb
db/migrate/20210624173908_change_query_logs_column_types.rb
db/structure.sql
spec/api/v1/sparql_spec.rb
spec/models/query_log_spec.rb

Payload is occasionally too large for JSONB columns. Change to plain text

Change column type for query logs query/result

---

app/api/base.rb
app/api/entities/publish_request.rb
app/api/v2/base.rb
app/api/v2/defaults.rb
app/api/v2/publish.rb
app/api/v2/publish_requests.rb
app/jobs/publish_envelope_job.rb
app/models/publish_request.rb
app/services/publish_interactor.rb
db/migrate/20210715141032_create_publish_requests.rb
db/structure.sql
spec/api/v2/publish_requests_spec.rb
spec/api/v2/publish_spec.rb
spec/factories/envelope_communities.rb
spec/factories/publish_requests.rb
spec/jobs/publish_envelope_job_spec.rb

This PR adds async publishing functionality to the CredReg API. The feature is implemented in the following way:
- A new API version, `v2`, was added with the routes:
- `POST /resources/organizations/:organization_id/documents`: publish on behalf (asynchronous)
- `GET /publish_requests`: list of current publish requests
- `GET /publish_requests/:id`: get publish request by ID
- API selection is done via the header `Accept-Version`.
- A new model was created, `PublishRequest`, which stores the original parameters for the envelope that is scheduled for publishing. `PublishRequest`s are updated whenever the publishing process completes (either successfully or with error).
- A new Sidekiq job `PublishEnvelopeJob` was created that calls `PublishInteractor` with the information stored in a …

Add async job for publishing envelopes

---

app/services/ctdl_query.rb

When checking for id presence in array derived from subquery there's no need for repeated values.

Optimize subqueries for CTDL engine

---

app/api/entities/envelope.rb
lib/swagger_docs.rb
spec/api/v1/envelopes_spec.rb
spec/api/v1/publish_spec.rb

If we need that feature we should store revisions invormation based on meaningful input (actual resource)
instead of relying on ephermal ActiveRecord instance state.

Remove changed flag from Envelope entity

---

.github/workflows/dependency-review.yaml

Quick tweak to avoid running into [this issue](https://github.com/actions/dependency-review-action/issues/456) when dependency-review runs against the `master` branch. We actually only need it for PRs, so we only trigger the action there.

Only run dependency review on pull requests
